const SatelliteLaunchSite = {
    AFETR: "launch_sites.afetr",
    AFWTR: "launch_sites.afwtr",
    CAS: "launch_sites.cas",
    ERAS: "launch_sites.eras",
    FRGUI: "launch_sites.frgui",
    HGSTR: "launch_sites.hgstr",
    JSC: "launch_sites.jsc",
    KODAK: "launch_sites.kodak",
    KSCUT: "launch_sites.kscut",
    KWAJL: "launch_sites.kwajl",
    KYMTR: "launch_sites.kymtr",
    NSC: "launch_sites.nsc",
    OREN: "launch_sites.oren",
    PKMTR: "launch_sites.pkmtr",
    PMRF: "launch_sites.pmrf",
    RLLC: "launch_sites.rllc",
    SADOL: "launch_sites.sadol",
    SEAL: "launch_sites.seal",
    SEM: "launch_sites.sem",
    SMTS: "launch_sites.smts",
    SNMLP: "launch_sites.snmlp",
    SRI: "launch_sites.sri",
    SVOB: "launch_sites.svob",
    SWAS: "launch_sites.swas",
    TNSTA: "launch_sites.tnsta",
    TSC: "launch_sites.tsc",
    TTMTR: "launch_sites.ttmtr",
    VOSTO: "launch_sites.vosto",
    VOWAS: "launch_sites.vowas",
    WLPIS: "launch_sites.wlpis",
    WOMRA: "launch_sites.womra",
    WRAS: "launch_sites.wras",
    WSC: "launch_sites.wsc",
    XSC: "launch_sites.xsc",
    YAVNE: "launch_sites.yavne",
    YSLA: "launch_sites.ysla",
    YUN: "launch_sites.yun",
    UNKN: "unknown",
};

export default SatelliteLaunchSite;
