enum SatelliteLaunchSite {
    AFETR = "Air Force ER 🇺🇸",
    AFWTR = "Air Force WR 🇺🇸",
    CAS = "Canary Islands 🇮🇨",
    ERAS = "Eastern Range 🇺🇸",
    FRGUI = "French Guiana 🇫🇷",
    HGSTR = "Hammaguira 🇩🇿",
    JSC = "Jiuquan 🇨🇳",
    KODAK = "Kodiak Island 🇺🇸",
    KSCUT = "Kagoshima 🇯🇵",
    KWAJL = "Kwajalein 🇲🇭",
    KYMTR = "Kapustin Yar 🇷🇺",
    NSC = "Naro 🇰🇷",
    OREN = "Orenburg 🇷🇺",
    PKMTR = "Plesetsk 🇷🇺",
    PMRF = "PMRF Barking Sands 🇺🇸",
    RLLC = "Rocket Lab",
    SADOL = "Barents Sea 🇺🇸",
    SEAL = "Sea Launch",
    SEM = "Semnan 🇮🇷",
    SMTS = "Shahrud 🇮🇷",
    SNMLP = "San Marco 🇮🇹",
    SRI = "Satish Dhawan 🇮🇳",
    SVOB = "Svobodny 🇷🇺",
    SWAS = "Cornwall 🇬🇧",
    TNSTA = "Tanegashima 🇯🇵",
    TSC = "Taiyaun 🇨🇳",
    TTMTR = "Baikonur 🇰🇿",
    UNKN = "Unknown",
    VOSTO = "Vostochny 🇷🇺",
    VOWAS = "Virgin Orbit",
    WLPIS = "Wallops Island 🇺🇸",
    WOMRA = "Woomera 🇦🇺",
    WRAS = "Western Range 🇺🇸",
    WSC = "Wenchang 🇨🇳",
    XSC = "Xichang 🇨🇳",
    YAVNE = "Yavne 🇮🇱",
    YSLA = "Yellow Sea 🇨🇳",
    YUN = "Yunsong 🇰🇵",
}

export default SatelliteLaunchSite;
